.TH Submin-admin 1 "March 2008" "Submin admin tool" "User Manuals"
.SH NAME 
submin-admin \- Submin administration tool
.SH SYNOPSIS
.B submin-admin
.I command
[
.I options
]

.B submin-admin
help
[
.I command
]

.SH OVERVIEW
Submin is a web-based adminstration interface for subversion. Submin-admin
is the administration tool to create a new Submin environment.

Please use the `help' command of submin-admin to access the built-in tool
documentation.

